# 
# Makefile by stoney
# for Rust programming
#
all: usage

usage:
	@echo ""
	@echo "make [edit|new|build|run]"
	@echo ""

PGM=hello

edit e:
	vi src/main.rs

edit-cargo ec:
	vi Cargo.toml

edit-make em:
	vi Makefile

edit-readme er:
	vi README.md

new n:
	@if [ ! -d "./src" ]; then \
		cargo new --bin $(PGM); \
	else \
		echo "Already created."; \
	fi

build b:
	cargo build

run r:
	cargo run

clean:
	cargo clean

version v:
	@cargo --version
	@rustc --version
	@rustdoc --version

