#
# Makefile by stoney
#
.PHONY: all usage

all : usage

usage:
	@echo ""
	@echo "usage: make [e:dit]"
	@echo ""

edit e:
	@echo ""
	@echo "make edit [blockchain:eb|multimedia:eu|webrtc:et|webassembly:ea]"
	@echo ""

edit-make em:	
	vi Makefile

edit-blockchain eb:
	vi Blockchain.md

edit-multimedia eu:
	vi Multimedia.md

edit-webrtc et:
	vi Multimedia.md

edit-webassemby ea:
	vi Multimedia.md

